#!/bin/bash
PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin
SERVICE=rtorrent
FILE=/home/$USER/.session/rtorrent.lock
MAX=95

df /home/$USER | tail -1 | while read fs size used avail pcnt mount
do
	pcnt=$(echo $pcnt | cut -d'%' -f1 )
	if [[ $pcnt -ge $MAX ]]; then
		echo "Running out of space \"$fs ($pcnt%)\" on $HOSTNAME as on $(date)"
		exit 1
	fi

	if pgrep -u $USER $SERVICE >/dev/null; then
		echo "$SERVICE service running, everything is fine"
	else
		rm -f /home/$USER/.dtach/rtorrent
		mkdir -p /home/$USER/.dtach && mkdir -p /home/$USER/.dtach/rtorrent
		rm -f $FILE
		echo "$SERVICE is not running, starting $SERVICE" && dtach -n /home/$USER/.dtach/rtorrent $SERVICE
	fi
done
